# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server import util


class SampleBody(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, file=None, delimiter=None):  # noqa: E501
        """SampleBody - a model defined in OpenAPI

        :param file: The file of this SampleBody.  # noqa: E501
        :type file: str
        :param delimiter: The delimiter of this SampleBody.  # noqa: E501
        :type delimiter: str
        """
        self.openapi_types = {
            'file': str,
            'delimiter': str
        }

        self.attribute_map = {
            'file': 'file',
            'delimiter': 'delimiter'
        }

        self._file = file
        self._delimiter = delimiter

    @classmethod
    def from_dict(cls, dikt) -> 'SampleBody':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The SampleBody of this SampleBody.  # noqa: E501
        :rtype: SampleBody
        """
        return util.deserialize_model(dikt, cls)

    @property
    def file(self):
        """Gets the file of this SampleBody.

        Ссылка на файл  # noqa: E501

        :return: The file of this SampleBody.
        :rtype: str
        """
        return self._file

    @file.setter
    def file(self, file):
        """Sets the file of this SampleBody.

        Ссылка на файл  # noqa: E501

        :param file: The file of this SampleBody.
        :type file: str
        """
        if file is None:
            raise ValueError("Invalid value for `file`, must not be `None`")  # noqa: E501

        self._file = file

    @property
    def delimiter(self):
        """Gets the delimiter of this SampleBody.

        Разделитель колонок в файле  # noqa: E501

        :return: The delimiter of this SampleBody.
        :rtype: str
        """
        return self._delimiter

    @delimiter.setter
    def delimiter(self, delimiter):
        """Sets the delimiter of this SampleBody.

        Разделитель колонок в файле  # noqa: E501

        :param delimiter: The delimiter of this SampleBody.
        :type delimiter: str
        """

        self._delimiter = delimiter
